import { StyleSheet } from 'react-native';

export const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9fafb',
  },
  innerContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 30,
  },
  logoImage: {
    width: 400,
    height: 200,
  },
  logoBackground: {
    width: 120,
    height: 120,
    backgroundColor: '#16a34a',
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  logoInner: {
    width: 100,
    height: 100,
    backgroundColor: '#34d399',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  logoDot: {
    width: 24,
    height: 24,
    backgroundColor: 'white',
    borderRadius: 12,
    position: 'absolute',
    top: 20,
    left: 36,
  },
  logoMouth: {
    width: 32,
    height: 20,
    backgroundColor: 'white',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    position: 'absolute',
    top: 40,
    left: 32,
  },
  logoText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'white',
    position: 'absolute',
    bottom: 16,
    right: 20,
  },
  logoBars: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    position: 'absolute',
    bottom: 16,
    left: 16,
  },
  logoBar1: {
    width: 4,
    height: 8,
    backgroundColor: 'white',
    marginRight: 2,
  },
  logoBar2: {
    width: 4,
    height: 12,
    backgroundColor: 'white',
    marginRight: 2,
  },
  logoBar3: {
    width: 4,
    height: 6,
    backgroundColor: 'white',
  },
  formContainer: {
    width: '100%',
  },
  inputContainer: {
    marginBottom: 12,
  },
  input: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 17,
    color: '#1f2937',
  },
  button: {
    backgroundColor: '#16a34a',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginBottom: 16,
  },
  buttonDisabled: {
    backgroundColor: '#9ca3af',
    opacity: 0.7,
  },
  disabledButton: {
    backgroundColor: '#9ca3af',
    opacity: 0.7,
  },
  buttonText: {
    color: 'white',
    fontSize: 17,
    fontWeight: '600',
  },
  signupContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  signupText: {
    fontSize: 17,
    color: '#4b5563',
  },
  signupLink: {
    fontSize: 17,
    color: '#16a34a',
    fontWeight: '600',
  },
  codeSentContainer: {
    alignItems: 'center',
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  codeSentText: {
    fontSize: 17,
    color: '#4b5563',
    marginBottom: 8,
    textAlign: 'center',
  },
  changeNumberLink: {
    fontSize: 14,
    color: '#16a34a',
    fontWeight: '500',
  },
  codeInputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 8,
  },
  codeInputRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    gap: 20,
    marginBottom: 12,
  },
  codeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
    paddingHorizontal: 20,
  },
  codeInput: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    width: 45,
    height: 56,
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1f2937',
    textAlign: 'center',
    elevation: 2,
  },
  forgotCodeContainer: {
    alignSelf: 'flex-end',
    marginBottom: 28,
  },
  forgotCodeContainerDisabled: {
    opacity: 0.6,
  },
  forgotCodeLink: {
    color: '#16a34a',
    fontSize: 14,
    fontWeight: '500',
  },
  forgotCodeLinkDisabled: {
    color: '#9ca3af',
  },
  // Estilos para mensajes de error y éxito
  messageContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    marginBottom: 16,
  },
  errorContainer: {
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  successContainer: {
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  infoContainer: {
    backgroundColor: '#f0f9ff',
    borderWidth: 1,
    borderColor: '#bae6fd',
  },
  errorText: {
    color: '#dc2626',
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  successText: {
    color: '#16a34a',
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  infoText: {
    color: '#2563eb',
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  // Estilos adicionales para admin login
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1f2937',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#6b7280',
    textAlign: 'center',
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 6,
  },
  linkButton: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  linkText: {
    fontSize: 14,
    color: '#16a34a',
    fontWeight: '500',
  },
  errorMessage: {
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  successMessage: {
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  infoMessage: {
    backgroundColor: '#f0f9ff',
    borderWidth: 1,
    borderColor: '#bae6fd',
  },
  messageText: {
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  resendContainer: {
    alignItems: 'center',
    marginTop: 20,
  },
  resendText: {
    color: '#16a34a',
    fontSize: 16,
    fontWeight: '600',
  },
  timerText: {
    color: '#6b7280',
    fontSize: 14,
  },
  backButton: {
    marginTop: 30,
    alignItems: 'center',
  },
  backButtonText: {
    color: '#6b7280',
    fontSize: 16,
    fontWeight: '500',
  },
  logoSmall: {
    width: 60,
    height: 60,
    marginBottom: 10,
  },
  titleSmall: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: 5,
  },
});
